# Setup
title:               Tools of the Trade
tagline:             'Hosted by ACENET'
description:         'Event description'
url:                 ''
#baseurl:             '/lvermeyden'
baseurl:             '/'
permalink:           pretty

# About/contact
author:
  name:              Mark Otto
  url:               https://twitter.com/mdo
  email:             markdotto@gmail.com

# Gems
#plugins:


# Custom vars
version:             1.1.0
google_analytics_id: #UA-XXXX-Y
